### PR TITLE
fix: bullet的target支持回调函数处理

### LINKED ISSUE #2229: 子弹图 通过 size 回调设置 target 大小，会导致目标值消失
* **G2Plot Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

```ts
import { Bullet } from '@antv/g2plot';

const data = [
  {
    title: '重庆',
    ranges: [30, 90, 120],
    measures: [65],
    target: 80,
  },
  {
    title: '杭州',
    ranges: [30, 90, 120],
    measures: [50],
    target: 100,
  },
  {
    title: '广州',
    ranges: [30, 90, 120],
    measures: [40],
    target: 85,
  },
  {
    title: '深圳',
    ranges: [30, 90, 120],
    measures: [50],
    target: 100,
  },
];

const bulletPlot = new Bullet('container', {
  data,
  measureField: 'measures',
  rangeField: 'ranges',
  targetField: 'target',
  xField: 'title',
  color: {
    range: ['#FFbcb8', '#FFe0b0', '#bfeec8'],
    measure: '#5B8FF9',
    target: '#39a3f4',
  },
  label: {
    measure: {
      position: 'middle',
      style: {
        fill: '#fff',
      },
    },
  },
    size: {
       measure: ({ title }) => {
        return title === '广州' ? 10 : 20
      },
      // bug 设置后，导致 target 消失
    target: (args) => {
      return 20
    }
  },
  xAxis: {
    line: null,
  },
  yAxis: false,
});

bulletPlot.render();
```

### PR DESCRIPTION
**Pull request by arcsin1**
### PR includes

- [x] fixed #2229 
- [x] add / modify test cases

### CODE REVIEW

File: __tests__/bugs/issue-2229-spec.ts [hunk 1]
```diff
@@ -0,0 +1,66 @@
...
+    const bullet = new Bullet(createDiv('measureSize*rangeSize bullet'), {
+      width: 400,
+      height: 400,
+      data,
+      measureField: 'measures',
+      rangeField: 'ranges',
+      targetField: 'target',
+      xField: 'title',
+      size: {
+        range: (arg) => {
```
Comment (hustcc) [inline __tests__/bugs/issue-2229-spec.ts:41]: lint 修复
