### PR TITLE
fix: guideline Closes #1063

### LINKED ISSUE #1063: guideLine 配置无效
https://g2plot.antv.vision/zh/examples/general/guideLine#statistic-guideline

官网的代码演示也没有效果。

### PR DESCRIPTION
**Pull request by paleface001**

### CODE REVIEW

File: __tests__/bugs/issue-883-spec.ts [hunk 1]
```diff
@@ -9,7 +9,7 @@ describe('#883', () => {
   canvasDiv.id = 'canvas1';
   document.body.appendChild(canvasDiv);
 
-  it('guidline暂时只支持非转置坐标系', () => {
+  it.only('guidline暂时只支持非转置坐标系', () => {
```
Comment (zqlu) [inline __tests__/bugs/issue-883-spec.ts:12]: 这个漏了个 only

Comment (paleface001) [reply __tests__/bugs/issue-883-spec.ts]: done
