### PR TITLE
fix(histogram): binNumber 设置出错

### LINKED ISSUE #2695: 🐛 [BUG]直方图的最后一个分箱总是只有一个，且最后显示的分箱数量比binNumber大1
### 💻 Link to minimal reproduction

Please provide a link by forking these links [g2plot](https://codesandbox.io/s/g2plot-reproduction-template-gyej1) or GitHub repo. What is a minimal reproduction, and why is it required?

### 🚑 Any additional [like screenshots]

* **G2Plot Version**:
* **Platform**:

### PR DESCRIPTION
**Pull request by visiky**
### PR includes

- [x] fixed #2695 
- [x] add / modify test cases
- [x] documents, demos

### Screenshot

|  Before  |  After  |
|----|----|
|  ❌  |  ✅  |

### CODE REVIEW

File: src/utils/transform/histogram.ts [hunk 1]
```diff
@@ -41,7 +45,7 @@ export function binHistogram(data: Data, binField: string, binWidth: number, bin
   // 计算分箱，直方图分箱的计算基于 binWidth，如配置了 binNumber 则将其转为 binWidth 进行计算
   let _binWidth = binWidth;
   if (!binWidth && binNumber) {
-    _binWidth = rangeWidth / binNumber;
+    _binWidth = binNumber > 1 ? rangeWidth / (binNumber - 1) : range.max;
```
Comment (visiky) [inline src/utils/transform/histogram.ts:48]: 主要修改点

**Review by hustcc — APPROVED** [review]
