### PR TITLE
fix: pie tooltip

### LINKED ISSUE #2220: 饼图数据都为0的时候，tooltip 展示不一致
* **G2Plot Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

1.数组中都为0的时候
image

2.数组中有一个不为0的时候
image

### PR DESCRIPTION
**Pull request by visiky**
### PR includes

- [x] fixed #2220 
- [x] add / modify test cases
- [ ] documents, demos

### Screenshot

|  Before  |  After  |
|----|----|
|  image  |  image  |
|image|image|
|image|image|

### CODE REVIEW

File: src/plots/pie/adaptor.ts [hunk 1]
```diff
@@ -208,13 +206,30 @@ export function pieAnnotation(params: Params<PieOptions>): Params<PieOptions> {
...
+function tooltip(params: Params<PieOptions>): Params<PieOptions> {
+  const { chart, options } = params;
+  const { tooltip, colorField, angleField } = options;
+
+  if (tooltip === false) {
+    chart.tooltip(tooltip);
+  } else {
+    chart.tooltip(deepAssign({}, tooltip, { shared: false }));
+
+    const fields = get(tooltip, 'fields') || [colorField, angleField];
```
Comment (hustcc) [inline src/plots/pie/adaptor.ts:222]: > const fields = get(tooltip, 'fields', [colorField, angleField])

Comment (visiky) [reply src/plots/pie/adaptor.ts:222]: 不行🙅 null的时候也应该给他默认字段

**Review by hustcc — APPROVED** [review]
